import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FDFDFF' },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5EAF0',
  },
  backIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    tintColor: '#00041C',
  },
  headerTitle: { fontSize: 16, fontWeight: '600', color: '#00041C' },
  saveBtn: { fontSize: 15, fontWeight: '600', color: '#3281FF' },

  // 프로필 사진
  avatarWrap: { alignItems: 'center', paddingVertical: 32 },
  avatarContainer: { position: 'relative' },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#EEF4FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontSize: 28, fontWeight: '700', color: '#3281FF' },
  cameraBtn: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#fff',
    borderWidth: 0.5,
    borderColor: '#E5EAF0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraIcon: { fontSize: 13 },

  // 필드
  fieldWrap: { paddingHorizontal: 20, marginBottom: 20 },
  fieldLabel: { fontSize: 13, color: '#64748B', marginBottom: 8 },
  input: {
    borderWidth: 0.5,
    borderColor: '#E5EAF0',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#00041C',
    backgroundColor: '#FDFDFF',
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 0.5,
    borderColor: '#E5EAF0',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: '#FDFDFF',
  },
  dropdownText: { fontSize: 15, color: '#00041C' },
  dropdownArrow: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    tintColor: '#BEC8D6',
  },

  // 모달
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '70%',
    paddingBottom: 30,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E5EAF0',
  },
  modalTitle: { fontSize: 16, fontWeight: '600', color: '#00041C' },
  modalClose: { fontSize: 18, color: '#64748B' },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 0.5,
    borderBottomColor: '#F8FAFC',
  },
  modalItemActive: { backgroundColor: '#EEF4FF' },
  modalItemText: { fontSize: 15, color: '#00041C' },
  modalItemTextActive: { color: '#3281FF', fontWeight: '600' },
  modalArrow: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    tintColor: '#BEC8D6',
  },
});